#!/usr/bin/bash
#
# Copyright (C) 2025-2026 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cat <<EOY
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
  name: virt-cluster-validate
spec:
#  finally:
#    - name: cleanup
#      taskSpec:
#        metadata: {}
#        spec: null
#        stepTemplate:
#          computeResources: {}
#          image: 'quay.io/fdeutsch/virtualization-validation:latest'
#        steps:
#          - command:
#              - /app/cleanup
#            computeResources: {}
#            name: cleanup
  tasks:
EOY


PLUGINS=$(cat checks.d/generated-plugin-index.txt | grep -E "$PLUGIN_FILTER" | sort)
for PLUGIN in $PLUGINS
do
cat <<EOY
    - displayName: "$PLUGIN"
      name: plugin
      taskSpec:
        metadata: {}
        results:
          - name: stdout
            type: string
        spec: null
        stepTemplate:
          computeResources: {}
          env:
            - name: RESULT_STDOUT
              value: \$(results.stdout.path)
          image: '$PLUGIN'
        steps:
          - command:
              - /check.sh
              - main
            computeResources: {}
            name: check
      timeout: 2m0s
EOY
done
#            onError: continue

