#!/usr/bin/bash

#curl -sL http://downloads.openshift-console.svc.cluster.local/amd64/linux/oc.tar | tar xf -
#curl -sL http://hyperconverged-cluster-cli-download.openshift-cnv.svc.cluster.local:8080/amd64/linux/virtctl.tar.gz | tar xfz -
export PATH=$PATH:$PWD

c() { echo "# $@" ; }
n() { echo "" ; }
x() { echo "\$ $@" ; eval "$@" ; }
red() { echo -e "\e[0;31m$@\e[0m" ; }
green() { echo -e "\e[0;32m$@\e[0m" ; }
die() { red "FATAL: $@" ; exit 1 ; }
assert() { echo "(assert:) \$ $@" ; eval $@ || { echo "(assert?) FALSE" ; die "Assertion ret 0 failed: '$@'" ; } ; green "(assert?) True" ; }

export WD=${WD:-$PWD}
export BUILT_PLUGINS_INDEX="generated-plugin-index.txt"
export RESULTSD=${WD:-$PWD}/results.d/

main() {
  _gather_data
  #_display_data
}

_gather_data() {
  c "Starting validation ..."
  run_plugins $@
}

run_plugins() {
  local PLUGIN_FILTER="${1:-.*}"

  podman -r run \
      --rm \
      --env WD=/ \
      --env HOME=/ \
      --env RESULTSD=/results.d/ \
      --env NUM_CONCURRENT_TESTS=10 \
      --env TEST_FITER="$PLUGIN_FILTER" \
      --volume $PWD:/app:ro,z \
      --volume $PWD/results.d:/results.d:rw,z \
      --volume $HOME/.kube:/.kube:ro,z \
      --volume $(which oc):/usr/bin/oc:ro,bind,exec,z \
      --volume $(which virtctl):/usr/bin/virtctl:ro,bind,exec,z \
      fedora:latest \
      bash -e -c 'export PATH=$PATH:/app/bin ; prepare ; testrunner "$TEST_FILTER"'
}

_display_data() {
  c "Summarizing results from '$RESULTSD'"
  cat ${RESULTSD}/*/result.json \
  | jq -s . \
  | jq '{apiVersion: "validate.virtualization.openshift.com/v1alpha1", kind: "Results", items: .}' \
  | tee ${RESULTSD}/result.json \
  | pprint
}

pprint() {
    jq -r '
.items[]
| [
   if .step and .step.pass
   then "    \(.step.level) - \(.plugin.name)   + \(.check.displayname)@\(.step.name) - \(.step.message)"

   elif .check and .check.pass
   then "[x] PASS - \(.plugin.name) ### \(.check.displayname)"

   elif .check and .step

   then
     "    \(.step.level) - \(.plugin.name) --- \(.check.displayname)@\(.step.name) - \(.step.message)\n"
     + "[ ] FAIL - \(.plugin.name) ### \(.check.displayname)"
   end
] | join(" ")
'
}

if [[ "$1" == "run_check" ]];
then $@
else main $@
fi
